### ISSUE TITLE
API Functionality #7 out of 10

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/myhomecentral.net#1]
@codextiny
Please add API functionality to this new site. 

Credentials:
U: support@homeowner.ai
PW: M!l3st0nesL@bs

1. [Home Page]:(https://myhomecentral.net/)

- Update search bar with API functionality
- Add pop up form to Get Started Button in header on home page
- Add pop up form to CTA button in pre-footer 

2. [How it Works Page: ](https://myhomecentral.net/how-it-works/)

- Add pop up form to CTA button in hero image
-  Add pop up form to CTA button in pre-footer

Please use primary color for the form

**Comment by shannonbaldwin** [comment]
@codextiny

Please also make this section of home page (the search bar) mobile responsive. 

![image](https://github.com/user-attachments/assets/a1ce0f3e-16f0-43ce-a9ca-203c843afbbd)

**Comment by codextiny** [comment]
@shannonbaldwin 

we have updated the api popup functionality on both home page and how it works page, please check .

also search about bar mobile responsive, there is no default option from elementor so we need to make it responsive with custom code. you can see in screenshot.
![image](https://github.com/user-attachments/assets/f37b0924-d3ba-4770-a246-4a601bfb7a29)

so let us know if you want custom code to make search bar responsive.

Thanks

**Comment by shannonbaldwin** [comment]
yes, please make responsive.

**Comment by codextiny** [comment]
@shannonbaldwin 

please check .

**Comment by shannonbaldwin** [comment]
@codextiny Mobile view of search bar looks great.

We just need the form button colors on pop up to be the primary color #005A7C (see original GH). 

![image](https://github.com/user-attachments/assets/f9dd4342-5bf7-4180-ba8e-a2aaa465528e)![image](https://github.com/user-attachments/assets/7cece2c5-8b34-48b8-8302-36348f7c73d8)

**Comment by codextiny** [comment]
@shannonbaldwin 

done, please check

**Comment by shannonbaldwin** [comment]
@codextiny

We have updated the info on this site for API to connect to the right place but it is still creating routing to My Home Made Easy, not My Home Central. Is there something that needs to be updated on your end? This is what we updated.

![image](https://github.com/user-attachments/assets/5287a5a1-c5e6-4a3a-834f-43bd6c04c3ea)

**Comment by codextiny** [comment]
@shannonbaldwin 

can you please explain, where its creating route to my home made easy.
can you please give us screenshot.

We made request but its going from myhomecentral.net
![image](https://github.com/user-attachments/assets/843a91f3-c0f1-4aad-b283-b6e87838a710)
![image](https://github.com/user-attachments/assets/736d7745-5731-4307-9651-95812a931129)


Please check and reply accordingly.

**Comment by shannonbaldwin** [comment]
@codextiny It is working now! Maybe it just takes up to 24 hours to work.
